### ISSUE TITLE
strange prints with source_formulas_extractors.extract_source_formulas()

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-parsers#9] opened 2016-01-25 17:18 UTC
I've got below prints when I'm running the function which I think I didn't have before :

```

An exception occurred in node:
Node(classdef, [Leaf(1, 'class'), Leaf(1, 'rsa_majore_eligibilite'), Leaf(7, '('), Leaf(1, 'Variable'), Leaf(8, ')'), Leaf(11, ':'), Node(suite, [Leaf(4, '\n'), Leaf(5, '    '), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'column'), Leaf(22, '='), Leaf(1, 'BoolCol')]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'entity_class'), Leaf(22, '='), Leaf(1, 'Familles')]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'label'), Leaf(22, '='), Leaf(3, 'u"Eligibilit\xc3\xa9 au RSA major\xc3\xa9 pour parent isol\xc3\xa9"')]), Leaf(4, '\n')]), Node(funcdef, [Leaf(1, 'def'), Leaf(1, 'function'), Node(parameters, [Leaf(7, '('), Node(typedargslist, [Leaf(1, 'self'), Leaf(12, ','), Leaf(1, 'simulation'), Leaf(12, ','), Leaf(1, 'period')]), Leaf(8, ')')]), Leaf(11, ':'), Node(suite, [Leaf(4, '\n'), Leaf(5, '        '), Node(funcdef, [Leaf(1, 'def'), Leaf(1, 'has_enfant_moins_3_ans'), Node(parameters, [Leaf(7, '('), Leaf(8, ')')]), Leaf(11, ':'), Node(suite, [Leaf(4, '\n'), Leaf(5, '            '), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'age_holder'), Leaf(22, '='), Node(power, [Leaf(1, 'simulation'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'compute')]), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(3, "'age'"), Leaf(12, ','), Leaf(1, 'period')]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'smic55_holder'), Leaf(22, '='), Node(power, [Leaf(1, 'simulation'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'compute')]), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(3, "'smic55'"), Leaf(12, ','), Leaf(1, 'period')]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'age_enf'), Leaf(22, '='), Node(power, [Leaf(1, 'self'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'split_by_roles')]), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(1, 'age_holder'), Leaf(12, ','), Node(argument, [Leaf(1, 'roles'), Leaf(22, '='), Leaf(1, 'ENFS')])]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'smic55_enf'), Leaf(22, '='), Node(power, [Leaf(1, 'self'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'split_by_roles')]), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(1, 'smic55_holder'), Leaf(12, ','), Node(argument, [Leaf(1, 'roles'), Leaf(22, '='), Leaf(1, 'ENFS')])]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'nbenf'), Leaf(22, '='), Node(power, [Leaf(1, 'nb_enf'), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(1, 'age_enf'), Leaf(12, ','), Leaf(1, 'smic55_enf'), Leaf(12, ','), Leaf(2, '0'), Leaf(12, ','), Leaf(2, '2')]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(return_stmt, [Leaf(1, 'return'), Node(comparison, [Leaf(1, 'nbenf'), Leaf(21, '>'), Leaf(2, '0')])]), Leaf(4, '\n')]), Leaf(6, '')])]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'period'), Leaf(22, '='), Node(power, [Leaf(1, 'period'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'this_month')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'isol'), Leaf(22, '='), Node(power, [Leaf(1, 'simulation'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'calculate')]), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(3, "'isol'"), Leaf(12, ','), Leaf(1, 'period')]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'isolement_recent'), Leaf(22, '='), Node(power, [Leaf(1, 'simulation'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'calculate')]), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(3, "'rsa_isolement_recent'"), Leaf(12, ','), Leaf(1, 'period')]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'enfant_moins_3_ans'), Leaf(22, '='), Node(power, [Leaf(1, 'has_enfant_moins_3_ans'), Node(trailer, [Leaf(7, '('), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'enceinte_fam'), Leaf(22, '='), Node(power, [Leaf(1, 'simulation'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'calculate')]), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(3, "'enceinte_fam'"), Leaf(12, ','), Leaf(1, 'period')]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'nbenf'), Leaf(22, '='), Node(power, [Leaf(1, 'simulation'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'calculate')]), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(3, "'nb_enfant_rsa'"), Leaf(12, ','), Leaf(1, 'period')]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'rsa_eligibilite_tns'), Leaf(22, '='), Node(power, [Leaf(1, 'simulation'), Node(trailer, [Leaf(23, '.'), Leaf(1, 'calculate')]), Node(trailer, [Leaf(7, '('), Node(arglist, [Leaf(3, "'rsa_eligibilite_tns'"), Leaf(12, ','), Leaf(1, 'period')]), Leaf(8, ')')])])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(expr_stmt, [Leaf(1, 'eligib'), Leaf(22, '='), Node(atom, [Leaf(7, '('), Node(term, [Leaf(1, 'isol'), Leaf(16, '*'), Node(atom, [Leaf(7, '('), Node(expr, [Leaf(1, 'enceinte_fam'), Leaf(18, '|'), Node(atom, [Leaf(7, '('), Node(comparison, [Leaf(1, 'nbenf'), Leaf(21, '>'), Leaf(2, '0')]), Leaf(8, ')')])]), Leaf(8, ')')]), Leaf(16, '*'), Node(atom, [Leaf(7, '('), Node(expr, [Leaf(1, 'enfant_moins_3_ans'), Leaf(18, '|'), Leaf(1, 'isolement_recent'), Leaf(18, '|'), Leaf(1, 'enceinte_fam')]), Leaf(8, ')')]), Leaf(16, '*'), Leaf(1, 'rsa_eligibilite_tns')]), Leaf(8, ')')])]), Leaf(4, '\n')]), Node(simple_stmt, [Node(return_stmt, [Leaf(1, 'return'), Node(testlist, [Leaf(1, 'period'), Leaf(12, ','), Leaf(1, 'eligib')])]), Leaf(4, '\n')]), Leaf(6, '')])]), Leaf(6, '')])])
```

**Comment by cbenz** [comment] 2016-01-28 10:00
Can you provide more context on what provokes the error? (ie What script did you run? Or which request from the Web API?)

**Comment by adrienpacifico** [comment] 2016-01-28 12:04
This should provide the same output :

```
from openfisca_france.tests.base import tax_benefit_system
from openfisca_parsers import source_formulas_extractors
source_list = source_formulas_extractors.extract_source_formulas(tax_benefit_system, "ip_net")
```

**Comment by MattiSG** [comment] 2017-03-21 14:51
Duplicate of #5.

**Closed as completed by MattiSG** 2017-03-21 14:51 UTC
